spring:
  datasource:
    url: ${JARI_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JARI_DB_USERNAME}
    password: ${JARI_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: never